### ISSUE TITLE
TO DO!

### ISSUE THREAD

**Issue by Shoram444** [Shoram444/SNSensitivityEstimate#14]
**Tasks in TO DO list:**
==================
**Simulation**
- [x] Generate data 

1. **DONE**: So far, only internal bkg processes + standard $2\nu\beta\beta$ has been generated using mock calibration
2. **DONE**: simulate additional Xi31 process and use Simulated energy (will be used for energy smearing with realistic resolution of ~11%)
- [x] Plotting raw spectra: #2 
- try using makie
- [ ] [Check the values of the parameters used Issue: #3](https://github.com/Shoram444/SNSensitivityEstimate/issues/3)

- [ ] [Check the values of the parameters used](https://github.com/Shoram444/SNSensitivityEstimate/issues/10)
- [ ] Include radon

- [ ] Create notebooks with the detailed analysis with text
- [ ] [Convert to Falaise module](https://github.com/Shoram444/SNSensitivityEstimate/issues/11)
- [ ] Add vertex distance to the list of data-cuts? #6
- [ ] Resolution: [Issue:#7](https://github.com/Shoram444/SNSensitivityEstimate/issues/7)
    - [ ] energy loss in gas, long-term, depends on Filip's work
- [ ] Figure out tracking for bkg processes
- [ ] [3D ROI search Issue:#8](https://github.com/Shoram444/SNSensitivityEstimate/issues/8)
- [ ] [StoB maps implement s/s(b) Issue:#9](https://github.com/Shoram444/SNSensitivityEstimate/issues/9)
- [ ] Does it make sense to obtain efficiency for single-electron channel by dividing by `2*nTotSim`? 

**IN PROGRESS**
================

- [ ] [Calculate FC sensitivity, MPFC Issue:#5](https://github.com/Shoram444/SNSensitivityEstimate/issues/5)

- [ ] change Process to take in Params Dict: isoName, signal, Activity, Tmeas, ...

**FINISHED TASKS**
================
- [x] Change `let` blocks to `with()` blocks
- [x] [Pull the number of expected background events from the Signal-over-background maps Issue:#4](https://github.com/Shoram444/SNSensitivityEstimate/issues/4)
- [x] Create framework for calculating efficiency maps
- [x] Convert efficiency maps to Signal-over-background maps
- [x] Find best ROI based on Signal-over-background maps
- [x] Present the work on analysis meetings:

- First analysis planned for Wednesday 22nd November: DocDB#[5833](http://nile.hep.utexas.edu/cgi-bin/DocDB/ut-nemo/private/ShowDocument?docid=5833)

**OUT-OF-FIELD TASKS**
================
- [ ] continue Absolute angles study - distance of electrons travelled vs direction scattering
- [ ]
