### ISSUE TITLE
Use BAT.jl For fitting

### ISSUE THREAD

**Issue by Shoram444** [Shoram444/SNSensitivityEstimate#18]
8GOAL
========
Prepare fitting framework. One option is to use `BAT.jl`. 

PROCEDURE
========

## 0nubb: 

parameters to fit:
- **Expected total number of signal counts** $\mu^S$: 

$$ \mu^S = m t \varepsilon_S S $$

$$ [S] = kg^{-1}yr^{-1} $$

$$ \mu^S = ln(2) \frac{N_A a m t }{W} \varepsilon S $$
with
$$ S = \frac{1}{T_{1/2}} $$ 

- **Expected total number of background counts** $\mu^B$ : 

$$ \mu^B = m t \Delta E BI $$
$$ [BI] = kg^{-1}yr^{-1}keV^{-1} $$

...

To perform the fit:
   1. generate data from _expected background counts_ which can be obtained from the background model 
   
$\rightarrow$ for each bin $n_i = rand(Poisson(\bar{b_i}))$
   
   2. perform BAT fit and obtain 90% CI on S
   3. Convert to T12
   4. repeat N times - get T12 at 90% and median

**Comment by Shoram444** [comment]
Use https://github.com/JuliaPhysics/RadiationSpectra.jl to get better fit model from histograms

**Comment by Shoram444** [comment]
# Bayesian Fitting of MC-Derived Histograms with Uncertainties (1D & 2D)

## Summary
This issue tracks the implementation of Bayesian fits using **RadiationSpectra.jl** and **BAT.jl**, focusing on:  
1. **Fitting MC-derived signal/background histograms** instead of parametric distributions.  
2. **Extending the method to 2D histograms** (e.g., energy pairs).  
3. **Incorporating statistical uncertainties** from finite MC statistics.  

## Implementation Steps

### **1. Bayesian Fit Using 1D MC Histograms**
- Convert **MC-derived histograms** (signal & background) into **probability distributions**.  
- Use **Dirichlet priors** for mixture fractions.  
- Define a **log-likelihood** using categorical sampling from histograms.  
- Perform Bayesian inference with **BAT.jl**.  

```julia
using BAT, RadiationSpectra, Distributions, StatsBase, Random, Plots

# Simulated MC data (replace with real MC histograms)
Random.seed!(42)
signal_samples = rand(Normal(2.0, 0.8), 5000)
background_samples = rand(Exponential(1.5), 5000)

# Convert to RadiationSpectra histograms
signal_spectrum = Spectrum1D(signal_samples, bins=50, normalize=true)
background_spectrum = Spectrum1D(background_samples, bins=50, normalize=true)

# Extract probabilities
signal_probs = signal_spectrum.counts ./ sum(signal_spectrum.counts)
background_probs = background_spectrum.counts ./ sum(background_spectrum.counts)

# Define log-likelihood for Bayesian fit
function log_likelihood(params)
    w_signal, w_background = params[:weights]
    mixture_probs = w_signal .* signal_probs .+ w_background .* background_probs
    mixture_probs ./= sum(mixture_probs)
    return sum(logpdf(Categorical(mixture_probs), d) for d in data)
end

# Define priors
prior = NamedTupleDist((
    weights = Dirichlet(ones(2))
))

# Perform Bayesian inference
posterior = PosteriorMeasure(log_likelihood, prior)
samples = bat_sample(posterior, MCMCSampling(mcalg=:metropolis, nsteps=20000))

# Plot results
plot(samples)
```


### **2. Extending to 2D Histograms (Energy Pairs)**
- Use **2D histograms from MC** to model signal and background.  
- Convert these histograms into **joint probability distributions**.  
- Adapt the **log-likelihood** to work in **two dimensions**.  

```julia
# Convert MC data to 2D histograms
signal_spectrum = Spectrum2D(signal_samples, bins=(30, 30), normalize=true)
background_spectrum = Spectrum2D(background_samples, bins=(30, 30), normalize=true)

# Extract probabilities
signal_probs = signal_spectrum.counts ./ sum(signal_spectrum.counts)
background_probs = background_spectrum.counts ./ sum(background_spectrum.counts)

# Define log-likelihood for 2D mixture
function log_likelihood(params)
    w_signal, w_background = params[:weights]
    mixture_probs = w_signal .* signal_probs .+ w_background .* background_probs
    mixture_probs ./= sum(mixture_probs)

    log_prob = sum(
        logpdf(Categorical(vec(mixture_probs)), find_bin_idx(bin_edges_x, d[1]), find_bin_idx(bin_edges_y, d[2]))
        for d in data
    )
    return log_prob
end
```

---

### **3. Incorporating MC Uncertainties**
- Instead of fixed bin probabilities, **model bin counts as Poisson variables**.  
- Modify the **log-likelihood** to reflect **Poisson-distributed MC statistics**.  

```julia
# Define log-likelihood with Poisson uncertainties
function log_likelihood(params)
    w_signal, w_background = params[:weights]
    expected_signal = w_signal * signal_counts
    expected_background = w_background * background_counts
    expected_total = expected_signal .+ expected_background

    log_prob = sum(logpdf(Poisson(expected_total[i]), signal_counts[i] + background_counts[i])
                   for i in eachindex(signal_counts))
    return log_prob
end
```

---

## **Next Steps**
- [ ] Implement **systematic uncertainty modeling** (e.g., calibration errors).  
- [ ] Compare **MCMC vs Nested Sampling** for efficiency.  
- [ ] Validate with **real experimental data**.  

---

### **Why This Approach Works**
✅ **Handles real MC-based distributions** instead of assuming parametric forms.  
✅ **Extends to 2D for joint energy spectrum fitting**.  
✅ **Incorporates Poisson uncertainties from MC statistics** for a more robust analysis.  

---

This issue serves as a roadmap for implementing **Bayesian fits with MC histograms using RadiationSpectra.jl and BAT.jl**. Let me know if you have any refinements! 🚀

**Comment by Shoram444** [comment]
Working example with histogram likelihood:

```julia
using Random, LinearAlgebra, Statistics, Distributions, StatsBase, Plots, BAT, BinnedModels, StatsBase, DensityInterface, IntervalSets, FHist
using SpecialFunctions

mu1 = 1000
lambda = 0.001
sigma1 = sqrt(mu1)
n1 = 1
n2 = 1000
n = n1 + n2
ε = 0.1
d1 = rand(Normal( mu1, sigma1), n1) .+ ε
d2 = rand(Uniform(0, 3000), n2) .+ ε

data = vcat(
    d1, d2
)

h1 = normalize(Hist1D(d1; binedges = 0:100:3000), width = true)
h2 = normalize(Hist1D(d2; binedges = 0:100:3000), width = true)



data_hist = Hist1D(data; binedges = 0:100:3000)

true_par_values = (a = n1/sum(bincounts(data_hist)), ε = 0.1)

plot(data_hist)

my_pdf(h::Hist1D, x::Real) = ismissing(lookup(h, x)) ? 0.0 : lookup(h, x)

function f(par::NamedTuple{(:a, :ε)}, x::Real)
    total_rate = sum(par.a)
    a1 = par.a[1]
    a2 = 1.0 - a1
    th = normalize(a1*h1 + a2*h2 , width = true)
    return my_pdf(th, x) 
end


prior = distprod(
    a = Uniform(0, 1),
    ε = 0.1
)

function log_pdf_poisson(λ::T, k::U) where {T<:Real,U<:Real}
    R = float(promote_type(T,U))
    if λ >= 0 && k >= 0 && isinteger(k)
        a = iszero(k) ? R(k) : R(log(λ) * k)
        lg = logabsgamma(k + 1)[1]
        R(a - λ - lg)
    else
        R(-Inf)
    end
end

function make_hist_likelihood(h::Hist1D, f::Function)
    logfuncdensity(function(p)
        # Histogram counts for each bin as an array:
        counts = bincounts(h)
        n = sum(counts)
        # Histogram binning, has length (length(counts) + 1):
        binning = binedges(h)

        # sum log-likelihood value over bins:
        ll_value::Float64 = eps(Float64)
        
        for i in eachindex(counts)

            # Get information about current bin:
            bin_left, bin_right = binning[i], binning[i+1]
            bin_width = bin_right - bin_left
            bin_center = (bin_right + bin_left) / 2

            observed_counts = counts[i]

            # Simple mid-point rule integration of fit function `f` over bin:
            expected_counts = bin_width * f(p, bin_center) * n
            expected_counts == 0.0 && continue

            log_pdf_poisson(expected_counts, observed_counts) == -Inf && continue
            # Add log of Poisson probability for bin:
            ll_value += log_pdf_poisson(expected_counts, observed_counts)
            
        end
        ll_value
        return ll_value
    end )
end

my_likelihood = make_hist_likelihood(data_hist, f)

posterior = PosteriorMeasure(my_likelihood, prior)
samples, evals = bat_sample(posterior, MCMCSampling(mcalg = MetropolisHastings(), nsteps = 10^5, nchains = 4))

marginal_modes = bat_marginalmode(samples).result
```
